name: progressbar2
description: A progress bar for Dart console apps.
version: 0.3.1
homepage: https://github.com/hacker1024/progressbar.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lint: ^1.5.3
